### ISSUE TITLE
Cannot upload any file over 6MB to self-hosted supabase storage via dashboard

### ISSUE THREAD

**Issue by fgh-james** [supabase/storage#538]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When uploading a file greater than 6MB in size to storage via the supabase dashboard in a self-hosted instance I receive the following error:
```
Failed to upload 6_3mb.pdf: tus: failed to resume upload, caused by [object ProgressEvent], originated from request (method: HEAD, url: http://localhost/upload/resumable/cHN5Y2hvc29jaWFsX2NvbnRlbnQvRkdIIGJ1c2luZXNzIGNhcmRfMjAyNDA4MTkgY29weSA2LnppcC9hMjNmYTM5Yy1kZmI0LTRhMjUtYjQzYS1iMDU2OGY2MGM4NGU, response code: n/a, response text: n/a, request id: n/a)
```

While the file is uploading, I receive this error multiple times in the browser console
```
HEAD http://localhost/upload/resumable/cHN5Y2hvc29jaWFsX2NvbnRlbnQvRkdIIGJ1c2luZXNzIGNhcmRfMjAyNDA4MTkgY29weSA2LnppcC9hMjNmYTM5Yy1kZmI0LTRhMjUtYjQzYS1iMDU2OGY2MGM4NGU net::ERR_CONNECTION_REFUSED
```

I made sure to pull the latest docker images. This does not resolve the error.

## To Reproduce

1. Create a file that is 6MB in size
2. Go to the self-hosted supabase dashboard: localhost:8000
3. Go to storage, and upload the file
4. It will show its uploading for a moment, then error out with the error above.

## Expected behavior

Files up to 50MB should be able to be uploaded.

## Screenshots

While uploading

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/2d55abfd-d495-4fe2-95d2-87cbd6b7f245">

Error

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/edbaf107-4ec4-443c-a9c4-7ab982398754">

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of supabase docker compose: 3.8
- Version of Node.js: v18.19.0

## Additional information

- I have tried this with other files, not just the one I am testing with. I receive the same error for anything over 6MB

**Comment by cjlryan** [comment]
I'm also having this issue, noted that your console error is missing the port used for uploading on local (usually it would be http://localhost:54321 rather than just http://localhost).

This looks similar to this bug: https://github.com/supabase/supabase/issues/15703

A potential temporary solution might be to downgrade a couple of versions, mine only stopped working after updating to the latest one (CLI version 1.192.5, Storage API 1.11.0)

**Comment by cjlryan** [comment]
@fgh-james so... I fixed this for me.

It may be a mismatch between different docker image versions. I deleted then reinstalled all the docker images and it works perfectly again.

I hope that works for you!

**Comment by major-winter** [comment]
Have you tried uploading the file using Postman?

**Comment by rickypid** [comment]
I also have the same problem reported by @djsisson

**Comment by rickypid** [comment]
Thank you @djsisson for your quick reply!!! 

My situation is as follows: 
`Client Dart -> Ngnix Rever Proxy -> Supabase Self-Hosted [ Kong -> Storage ] `

I have the same problem as described above: I make a request on `https://myhost/storage/v1/upload/resumable`, in the Location Header of the response I get `http://myhost/storage/v1/upload/resumable/dGVzdC1leHBsb3Jlci90ZXN0LzQxMTQ3OTctdWhkXzM4NDBfMjE2MF8yNWZwcy5tcDQvODdlZDFkODYtYjZhMS00NTJhLWJkOGEtMmY3MTdlYzk1NTAx
`

**Comment by rickypid** [comment]
I solved it by inserting in my proxy rever configuration 🍾 🍾 🍾 :

`        proxy_redirect http://myhost:8000/ https://myhost/;`

**Comment by rallisf1** [comment]
I spend a full day on this, tried every possible fix I could find. I couldn't get rid of the `8000` port number in the request, so I used it! My dirty hack:

### kong.yml
```yaml
  ## Storage routes: the storage server manages its own auth
  - name: storage-v1
    _comment: 'Storage: /storage/v1/* -> http://storage:5000/*'
    url: http://storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - 'Forwarded: host=\$(headers.host)/storage/v1;proto=https'

  ## Fix Storage large uploads
  - name: storage-fix
    _comment: 'Storage: /storage/v1:8000/* -> http://storage:5000/*'
    url: http://storage:5000/
    routes:
      - name: storage-fix-all
        strip_path: true
        paths:
          - /storage/v1:8000/
    plugins:
      - name: cors
```

It's ugly AF but it works and I can finally go to sleep.

P.S. Kong might be a great Enterprise choice but the FOSS version is limited and most people are not familiar with it. I'm pretty sure this bug is left in here on purpose (you can find issues over a year ago!) while the SaaS uses `request-transformer-advanced` to fix this in a single rule...
