### ISSUE TITLE
SignatureDoesNotMatch Error on Self-hosted Supabase with S3 Protocol

### ISSUE THREAD

**Issue by baptiste-mnh** [supabase/storage#572]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.  
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

When attempting to upload files using the S3 protocol with Boto3 in a self-hosted Supabase environment, I receive a `403 SignatureDoesNotMatch` error. The same bucket is accessible from Supabase Studio, but Boto3 requests return an error related to mismatched request signatures.

Error from Boto3:

```
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListObjectsV2 operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Error log from the Supabase storage server:

```
{
  "level": 40,
  "time": "2024-10-16T12:51:46.481Z",
  "pid": 1,
  "hostname": "ip-10-0-XXX-XXX.eu-west-3.compute.internal",
  "region": "eu-west-3",
  "tenantId": "stub",
  "project": "stub",
  "reqId": "req-9g",
  "type": "request",
  "req": {
    "region": "eu-west-3",
    "traceId": "req-9g",
    "method": "GET",
    "url": "/s3/my-bucket?list-type=2&encoding-type=url",
    "headers": {
      "host": "storage.supabase.internal:5000",
      "x_forwarded_proto": "http",
      "x_forwarded_host": "staging.xxxxxxx.com",
      "x_forwarded_port": "8000",
      "x_real_ip": "10.0.47.203",
      "user_agent": "Boto3/1.35.41 md/Botocore#1.35.41 ua/2.0 os/macos#24.0.0 md/arch#arm64 lang/python#3.13.0 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.35.41"
    },
    "hostname": "storage.supabase.internal:5000",
    "remoteAddress": "10.0.XXX.XXX",
    "remotePort": 57368
  },
  "res": {
    "statusCode": 403,
    "headers": {
      "content_type": "application/xml; charset=utf-8",
      "content_length": "266"
    }
  },
  "responseTime": 2.8003710000775754,
  "error": {
    "raw": "{\"metadata\":{},\"code\":\"SignatureDoesNotMatch\",\"httpStatusCode\":403,\"userStatusCode\":400}",
    "name": "Error",
    "message": "The request signature we calculated does not match the signature you provided. Check your key and signing method.",
    "stack": "Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n at Object.SignatureDoesNotMatch (/app/dist/internal/errors/codes.js:140:39)\n at Object.<anonymous> (/app/dist/http/plugins/signature-v4.js:72:34)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "resources": ["/my-bucket"],
  "msg": "stub | GET | 403 | 10.0.146.76 | req-9g | /s3/my-bucket?list-type=2&encoding-type=url | Boto3/1.35.41 md/Botocore#1.35.41 ua/2.0 os/macos#24.0.0 md/arch#arm64 lang/python#3.13.0 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.35.41"
}
```

## To Reproduce

1. Set up a self-hosted Supabase environment with S3 as the storage backend, using Kong as a Gateway.
2. The Kong configuration for the `/storage/v1/` path is as follows:

   ```yaml
   - name: storage-v1
     _comment: "Storage: /storage/v1/* -> http://storage:5000/*"
     url: http://storage.supabase.internal:5000/
     routes:
       - name: storage-v1-all
         strip_path: true
         paths:
           - /storage/v1/
     plugins:
       - name: cors
   ```

3. The endpoint URL `https://staging.xxxxxxxxxxxx.com` corresponds to the Kong Gateway.

4. Configure the storage container with the following environment variables in Docker:

   ```yaml
   POSTGREST_URL: `${rest.endpoint}`,
   PGOPTIONS: "-c search_path=storage,public",
   TENANT_ID: "stub",
   IS_MULTITENANT: "false",
   REGION: eu-west-3,
   ENABLE_IMAGE_TRANSFORMATION: "true",
   IMGPROXY_URL: imgproxy.endpoint,
   WEBHOOK_URL: cacheManager.url,
   ENABLE_QUEUE_EVENTS: "false",
   
   # S3 Configuration
   S3_PROTOCOL_PREFIX: "/storage/v1",
   S3_PROTOCOL_ACCESS_KEY_ID: <value used by boto>,
   S3_PROTOCOL_ACCESS_KEY_SECRET: <value used by boto>,
   STORAGE_S3_BUCKET: <name of the bucket in AWS S3>,
   STORAGE_BACKEND: "s3",
   STORAGE_S3_MAX_SOCKETS: "200",
   STORAGE_S3_FORCE_PATH_STYLE: "true",
   FILE_SIZE_LIMIT: "52428800",
   TUS_URL_PATH: "/upload/resumable",
   TUS_URL_EXPIRY_MS: "86400000",
   UPLOAD_SIGNED_URL_EXPIRATION_TIME: "86400000",
   ```

5. Try listing the objects in the bucket using Boto3 with the following Python code:

   ```python
   import boto3

   s3 = boto3.client(
       's3',
       endpoint_url="https://staging.xxxxxxxxxxxx.com/storage/v1/s3",
       aws_access_key_id="*********************",
       aws_secret_access_key="******************************************",
       region_name="eu-west-3",
       config=Config(s3={"addressing_style": "path"})
   )

   def list_bucket_objects(bucket_name):
       response = s3.list_objects_v2(Bucket=bucket_name)
       if 'Contents' in response:
           for obj in response['Contents']:
               print(obj['Key'])
       else:
           print("Empty bucket")

   list_bucket_objects("my-bucket") # this bucket is visible in Supabase Studio
   ```
I've of course verified that "my-bucket" exists as this page show me its content :   https://staging.xxxxxxxx.com/project/default/storage/buckets/my-bucket

6. Receive the `403 SignatureDoesNotMatch` error.

## Expected behavior

Boto3 should be able to interact with the bucket and list objects without returning a signature mismatch error, as the correct access keys are provided.

## System information

- OS: macOS
- Version of Boto3: 1.35.41
- Supabase version: v1.11.14, also tested with v1.10.1

## Additional context

- I have attempted to follow solutions provided in related issues, such as [Issue #533](https://github.com/supabase/storage/issues/533), but the problem persists.
- The storage container logs indicate that the access keys are correct, and the bucket is accessible via Supabase Studio.

Thanks in advance!
